services:
  backend:
    container_name: backend
    # Configuration for building the docker image for the backend service
    build:
      context: ./backend # Use an image built from the specified dockerfile in the `app` directory.
      dockerfile: Dockerfile
    ports:
      - "2026:2026" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - dat # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://dat:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '82:80'
    expose:
      - '82'


  dat:
    image: mysql:latest
    container_name: dat
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:

