spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_events?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 464000000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 2026